version: 2.1
description: Re-usable AWS CLI with support for multiple profiles

executors:
  cli:
    working_directory: ~/repo
    docker:
      - image: sbstjn/go
jobs:
  exec:
    executor: cli
    parameters:
      Command:
        type: string
      Profile:
        type: string
        default: default
      AccessKey:
        type: string
      SecretKey:
        type: string
    steps:
      - attach_workspace:
          at: ~/repo
      - run: 
          name: Configure AWS Access Key
          command: aws configure --profile <<parameters.Profile>> set aws_access_key_id "<<parameters.AccessKey>>"
      - run: 
          name: Configure AWS Secret Key
          command: aws configure --profile <<parameters.Profile>> set aws_secret_access_key "<<parameters.SecretKey>>"
      - run: 
          name: Execute
          command: <<parameters.Command>>
